### ISSUE TITLE
Geofence stopped working.

### ISSUE THREAD

**Issue by amit-semusi** [CleverTap/clevertap-android-sdk#204]
Sometimes it works as expected, sometimes it stopped working till i reboot my device.

problem i am seeing when it stopped working, then receiver is not getting invoke.

try {

            CTGeofenceAPI.getLogger().debug(CTGeofenceAPI.GEOFENCE_LOG_TAG,
                    "Geofence receiver called");

       

this block is not execute when geofence stop working.
every time when this block execute and app gets data from intent then geofence works as expected.

It happens very randomly, almost every time I have to restart my device to make it working.

Device Details
Name : Redmi 9A
Version : 10.0

Vivo 1726
version : 8.1.0

**Comment by piyush-kukadiya** [comment]
@amit-semusi Can you use [fake GPS app](https://play.google.com/store/apps/details?id=com.lexa.fakegps&hl=en_IN&gl=US) for proper testing as real time notifications can be dropped by OEMs due to battery related restrictions due to which it's impossible to come to any conclusion that the issue is with OEM or OS or CleverTap SDK or Google geofence service.

**Comment by darshanclevertap** [comment]
@amit-semusi Are you still facing this issue?
