### ISSUE TITLE
React native using SDK 4.4.0 and push personalization, notification displayed even on foreground mode

### ISSUE THREAD

**Issue by idrissakhi** [CleverTap/clevertap-android-sdk#250]
**Describe the bug**
When we send push notification through CleverTap we receive it, and it displayed directly on android even if the App is in foreground mode.

**To Reproduce**
1. Open Partoo app
2. User profile is created on CleverTap side
3. send push notification test with the app running on foreground
4. the notification is displayed above the running app

**Expected behavior**
If the App State is forground then the notification should not appear 

**Screenshots/Logs**
In case of crashes, share the entire crash logs as a `.txt` file

**Environment (please complete the following information):**
 - Device: Android devices
 - OS: All
 - CleverTap SDK Version 4.4.0

**Additional context**
using push notification customization 
on android manifest we have

`        <service
            android:name=".MainNotificationService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>`

and inside that service we have 

`
package com.partoo.mobile;

import androidx.annotation.NonNull;

import com.clevertap.android.sdk.pushnotification.fcm.CTFcmMessageHandler;
import com.clevertap.android.sdk.pushnotification.fcm.FcmMessageListenerService;
import com.google.firebase.messaging.RemoteMessage;
import com.intercom.reactnative.IntercomModule;

public class MainNotificationService extends FcmMessageListenerService {

    private CTFcmMessageHandler mHandler = new CTFcmMessageHandler();

    @Override
    public void onMessageReceived(@NonNull RemoteMessage message) {
        if (IntercomModule.isIntercomPush(message)) {
            IntercomModule.handleRemotePushMessage(getApplication(), message);
        } else {
            mHandler.createNotification(getApplicationContext()., message);
        }
    }

    @Override
    public void onNewToken(@NonNull String token) {
        super.onNewToken(token);
        IntercomModule.sendTokenToIntercom(getApplication(), token);
        mHandler.onNewToken(getApplicationContext(), token);
    }
}
`

**Comment by darshanclevertap** [comment]
@idrissakhi What do you think the expected behavior should be when the app is in the foreground?

As per CleverTap, when a test push notification or a normal push notification is sent and the app is in the foreground then the Push Notification will still be rendered as a heads-up notification and then it will reside in the tray.

**Comment by darshanclevertap** [comment]
@idrissakhi 

CleverTap sends Data Push notifications via FCM and hence the `onMessageReceived` method will be called in all states, i.e - Foreground and Background. When you send push notifications via Firebase, they send Notification payload messages and since there is no handling done for them inside `onMessageReceived` of your custom class, hence they are not getting rendered.

Currently, CleverTap will render the push notification in both foreground and background state, if you want you can check whether the app is in the foreground before calling CleverTap's `createNotification` method.
