### ISSUE TITLE
InApp: Starts MainActivity even we have opened another one on Android 12

### ISSUE THREAD

**Issue by AlexanderMikulich** [CleverTap/clevertap-android-sdk#321]
**Describe the bug**
InApp notification starts MainActivity(android.intent.action.MAIN) every time we tap on push notification even we have already opened another one.
In other words: in onNewIntent every time we get intents that open MainActivity { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x34000000 pkg=com.example.clevertaptest cmp=com.example.clevertaptest/com.example.clevertaptest.MainActivity (has extras) }

**To Reproduce**
1. Go to '[Campaigns/Mobile In-app/Some Campaign/What/Preview & Test]'
2. Click on 'Send test'

**Environment (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - CleverTap SDK Version v4.6.0

Is it possible to show In-app message in already opened activity?

**Comment by AlexanderMikulich** [comment]
If I got right on Android 12+ the library get startIntent to show in-App message? 
https://github.com/CleverTap/clevertap-android-sdk/blob/4bd82f28c7da232147f335959449278b0bf82867/clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/LaunchPendingIntentFactory.java#L46

**Comment by shivamsharma2710** [comment]
Hi @AlexanderMikulich 

Thanks for reporting the issue. Which version of CleverTap SDK, you're using?

**Comment by AlexanderMikulich** [comment]
CleverTap SDK Version v4.6.0

**Comment by shivamsharma2710** [comment]
@AlexanderMikulich 

This is an expected behaviour of CleverTap SDK because tapping on a push notification is a different action.
Also, this is not specific to android 12 but a common behaviour for all android versions.

If you can come up with a use case then we will discuss this internally.

**Comment by AlexanderMikulich** [comment]
On Android 11 and lower I have another behavior:
1. Cold App start
2. Show FirstActivity
3. Open SecondActivity
4. Get a push and tap on it
5. The library starts Broadcast receiver
6. The Broadcast receiver do some work and shows In-App messages.
Everything perfect and as expected.

On Android 12 as I described we have:
1. Cold App start
2. Show FirstActivity
3. Open SecondActivity
4. Get a push and tap on it
5. The tap runs Intent which every time open First(Launcher) Activity.
That is looked as unexpected restart from user perspective.

So I would say that Android 12+ has different behavior in case if the app has already opened not Launcher activity and we have see that in the library in `LaunchPendingIntentFactory`. That class has other flow for Android 12+

Maybe I missed some settings and we can behave on Android 12 the same as on Android 11? I would great if you point me on that.

**Comment by shivamsharma2710** [comment]
@AlexanderMikulich  

CleverTap SDK uses same intent-flags to create an intent across all android versions that are used to launch the activity when you tap on a notification. 

You may check intent-flags here,

- [Android 12 and Above](https://github.com/CleverTap/clevertap-android-sdk/blob/4bd82f28c7da232147f335959449278b0bf82867/clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/LaunchPendingIntentFactory.java#L52) 

- [Below Android 12](https://github.com/CleverTap/clevertap-android-sdk/blob/4bd82f28c7da232147f335959449278b0bf82867/clevertap-core/src/main/java/com/clevertap/android/sdk/pushnotification/CTPushNotificationReceiver.java#L56)


With respect to deep links, following is the expected behaviour after a click on a push notification:
- If a deep link is provided to launch an activity, CleverTap SDK will launch that activity.
- If the deep link left empty, the notification click will open the launcher activity of the app.

> **Note** : **Above behaviour would be same across all android versions.**

**Comment by darshanclevertap** [comment]
@AlexanderMikulich Closing this due to no response from your side. Please feel free to reopen if you are still facing the issue
