### ISSUE TITLE
Unable to receive notifications on Android 13

### ISSUE THREAD

**Issue by Damercy** [CleverTap/clevertap-android-sdk#359]
**Describe the bug**
I'm not getting any notifications despite using latest Clevertap Android SDK `4.7.0` & providing the notification permission during runtime.

**To Reproduce**
1. Add CT SDK `4.7.0` dependency to gradle.
2. Target SDK 33 & add `POST_NOTIFICATION` permission to manifest.
3. Ask for notification permission using `cleverTapAPI.promptPushPrimer(jsonObject)` using any style. (Interstitial/Alert)
4. Once permission is granted and we receive the callback in `onPushPermissionResponse`, create required notification channels using ` CleverTapAPI.createNotificationChannel(...)`.
5. Keep another android device having Android < 13 that is running your app & keep it ready with the same Clevertap profile.
6. Send a test notification from Clevertap dashboard.
7. You'll find notification will be received in device running < Android 13 but not on the one running Android 13.

**Expected behavior**
We should receive notifications on Android 13 as well.

**Screenshots/Logs**
Android doesn't show up any logs, however the clevertap dashboard shows `GCMNotRegistered` error for 1 device, I suppose? See attached ss.

**Environment (please complete the following information):**
 - Device: Pixel 6 Pro (Emulator)
 - OS: Android 13
 - CleverTap SDK Version: 4.7.0
 - Android Studio Version : Android Studio Dolphin | 2021.3.1 Patch 1 Build #AI-213.7172.25.2113.9123335, built on September 30, 2022 Runtime version: 11.0.13+0-b1751.21-8125866 aarch64

**Additional context**
 Also attached emulator details, in case it's useful.

<img width="994" alt="Screenshot 2022-11-11 at 01 11 02" src="https://user-images.githubusercontent.com/24220261/201191045-15ba4c1e-e814-477a-a4a8-24de32728bc9.png">

[avd_details.txt](https://github.com/CleverTap/clevertap-android-sdk/files/9984175/avd_details.txt)

**Comment by darshanclevertap** [comment]
@Damercy You are right, you should be able to receive the Push Notification on Android 13 devices as well.

This seems to be out of the purview of the SDK since there are no logs related to receiving/rendering the push notifications on the Android Studio console.

My suggestion is please raise a support ticket from the dashboard as shown below -> 

![Support Ticket from CleverTap Dashboard](https://user-images.githubusercontent.com/29622446/201580454-135ef1bc-fafb-46bf-9007-c5bb82662f54.gif)

Please mention this Github issue as well while raising the ticket!

Thanks!

**Comment by Damercy** [comment]
@darshanclevertap Sure let me do that. Thank you!
