### ISSUE TITLE
Why location show Unknown, Unknown.

### ISSUE THREAD

**Issue by gauravtyagi328** [CleverTap/clevertap-android-sdk#36]
I am using setLocation() method to update location. But only lat and long field value updated and location field value Unknown why?
![clevertap_location_issue](https://user-images.githubusercontent.com/11554243/68275516-e9251180-0091-11ea-8a11-875da3cd2690.png)

**Comment by darshanclevertap** [comment]
@gauravtyagi328 When you pass Lat/Long to setLocation method, we only update the Lat/Long field on the dashboard. The city-wise location on the dashboard is coming as unknown because we do a reverse IP lookup from the incoming requests from the SDK and then define the city-wise location. I suggest that you please contact support@clevertap.com and mention this GitHub issue there and we will help you fast track this problem.
Thanks!
