### ISSUE TITLE
Use Secure Preference and DB

### ISSUE THREAD

**Issue by jboxx** [CleverTap/clevertap-android-sdk#369]
**Is your feature request related to a problem? Please describe.**
Sensitive information exposed on the CleverTap SDK, preference should using secure preference since there's no one sure what client will sent to CleverTapAPI#onUserLogin

**Describe the solution you'd like**
As of security crypto was lowering down to [SDK v21](https://developer.android.com/jetpack/androidx/releases/security#security-crypto-1.1.0-alpha04), please consider to use [EncryptedSharedPreference](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences)

**Describe alternatives you've considered**
Use 3rd party library to make the SDK still available for v19

**Additional context**
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/3339451/205240773-b3a7e5f4-2dd6-48e0-9485-426bc5e65915.png">

**Comment by darshanclevertap** [comment]
@jboxx We are internally debating the use of Encrypted Shared Prefs for our SDK but since we support v19 and above, using this library is not a direct solution for us. Could you suggest 3rd party libs for versions below 21?
Meanwhile, to answer your question, we do use HTTPS when the `onUserLogin` API is used so your data is secure during transit.

**Comment by gerosprime** [comment]
> Could you suggest 3rd party libs for versions below 21?

Got the same situation of OP. Would providing a custom storage or abstraction for different storage or even custom sharedpreference/SQLite database be possible?
