### ISSUE TITLE
[Clevertap][ANR] Push notification causing ANR

### ISSUE THREAD

**Issue by adeelcheetay** [CleverTap/clevertap-android-sdk#397]
**Describe the bug**
Since the integration of CleverTap RenderMax SDK we are receiving reports of ANR on Crashlytics com.clevertap.android.pushsdk.setContentView.<clinit>

**To Reproduce**
No steps are available as it's produced on the end user devices.

**Expected behavior**
The app shouldn't produce ANR during the push rendering.

**Screenshots/Logs**
[ANR_session_6404CE1200FF00015B8334B4057FF113_DNE_0_v2_stacktrace.txt](https://github.com/CleverTap/clevertap-android-sdk/files/10894819/ANR_session_6404CE1200FF00015B8334B4057FF113_DNE_0_v2_stacktrace.txt)

**Environment (please complete the following information):**

- Device: [Samsung, Xiaomi, Vivo, INFINIX MOBILITY LIMITEDHUAWEI, Google]
- OS: [Android 12,11,13] 100% background state
- CleverTap SDK Version [v4.6.6] RenderMax: 1.0.2
- Android Studio Version [Android Studio Electric Eel | 2022.1.1]

**Additional context**
N/A

**Comment by piyush-kukadiya** [comment]
@adeelcheetay RenderMax ANR fix needed to make changes to CleverTap core **v4.7.5** and RenderMax **v1.0.3**. Also since CleverTap Push Templates depends on CleverTap core hence we released Push Templates **v1.0.8**.
So in short,

- If you are using RenderMax and core, you will have to update both versions for compatibility and fix to work properly.

- If you are using RenderMax and core and push templates then, you will have to update all three versions for compatibility and fix to work properly.

- If using react native, you will have to update CleverTap react-native to **v1.0.1** Also you will have to follow points 1 and 2 above.
