### ISSUE TITLE
Issue with dynamic variable

### ISSUE THREAD

**Issue by shah-nishant** [CleverTap/clevertap-android-sdk#46]
We followed the steps mentioned here: https://developer.clevertap.com/docs/ab-tests

But we are unable to fetch values from the experiments created on dashboard.

"ab_exps" key is never present in the response received from the server here 
https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-android-sdk/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java#L3244

**Comment by darshanclevertap** [comment]
@shah-nishant We will need more information regarding your CleverTap account to help debug this. I would suggest that you write to support@clevertap.com mentioning your issue and your CleverTap account information. Also mention this GitHub issue while writing to us so that we can take it up on priority. 🙂
