### ISSUE TITLE
Native Display Message

### ISSUE THREAD

**Issue by gauravtyagi328** [CleverTap/clevertap-android-sdk#48]
Can you provide any simple project on Native Display feature. We have checked doc but we are unable to understand how to create user interface face for all type banner(Simple Banner, Carousel Banner, Banner with icon and coustom)

**Comment by darshanclevertap** [comment]
@gauravtyagi328 ,

The Native Display feature is built for flexibility such that you just pass KV pairs from CleverTap. Using the predefined keys in your app, the values can be configured on CleverTap to allow you to change/update the native display of the app.
Each of the types of the banner is just pre-defined system keys which you can configure in the app to ensure the display is as per the banner you need.
These system keys can be found in our docs. As mentioned, you can add the custom keys as well per your needs. 
Let me know if you need any more help

**Comment by gauravtyagi328** [comment]
We created all types banner (Simple, carousel and with icon) but at launch
time  we are get only simple banner. Why this is happening?

**Comment by darshanclevertap** [comment]
You will receive the data on the trigger event on which you have made the campaign. 
If you are still facing issues, you can write in to support@clevertap.com with your account details and campaign details which are supposedly not working and mention this GitHub issue so that our support team can take it up on priority.
