### ISSUE TITLE
CleverTap Display Units reliability

### ISSUE THREAD

**Issue by kssilvoza** [CleverTap/clevertap-android-sdk#49]
Is there a more reliable way on getting display units from CleverTap? When you push an Event that corresponds to a Native Display, there are times that the listener set in setDisplayUnitListener is not triggered at all.

**Comment by darshanclevertap** [comment]
@kssilvoza Hi, sorry for the delay in this reply.
This seems to be more of a complete end to end issue rather than an SDK issue.
Could you please give us more details like your Account ID and Account token and the campaign which was not responding the way you wanted and mail it to support@clevertap.com and please mark this Github issue as well in the mail so that we can take it up on priority.
