### ISSUE TITLE
App Inbox: Refresh behaviour

### ISSUE THREAD

**Issue by smithc42** [CleverTap/clevertap-android-sdk#81]
Notes:
- I'm displaying the default App Inbox UI via `CleverTap.showAppInbox`

**If a message is sent from the web console, are you required to open the message notification before it appears in the inbox?**
- Currently, if I send a message from the web console and open the app (without opening the message notification) and enter the app inbox via `showAppInbox` I don't see the message.
- Similarly, if I send a message from the web console while the app inbox is open, it does not refresh.
- If I click on the message notification, then open app inbox via `showAppInbox` then the message appears.

Is this expected behaviour or should the message appear in the inbox automatically without interacting with the notification?

**Comment by darshanclevertap** [comment]
@smithc42 Yes, you need to click the Push Notification which you receive while sending a test Inbox Message from the CleverTap dashboard. This is the expected behavior.

When you run the Inbox Message campaign, the Inbox message is received by the SDK when the user launches the app.

I'd suggest reading up on our [tech](https://developer.clevertap.com/docs/android#section-app-inbox) and [user](https://docs.clevertap.com/docs/app-inbox#message-variants) documentation for detailed understanding.

**Comment by smithc42** [comment]
Hi @darshanclevertap , I've read the docs but I'm pretty sure it doesn't mention this behaviour (unless I missed it?). As a user, I would expect the App Inbox UI to refresh when a message arrives, rather than needing to open the notification to fetch the message. Or for the message to be fetched when `showAppInbox` is called after the message has been sent.

Thanks for clarifying.

**Comment by darshanclevertap** [comment]
@smithc42 Thank you for this feedback. I'll share this with my team internally and probably include it in future releases.
